services:
  lettarrboxd:
    image: ryanpage/lettarrboxd:latest
    container_name: lettarrboxd
    environment:
      # Required variables
      - LETTERBOXD_URL=https://letterboxd.com/your_username/watchlist/
      - RADARR_API_URL=http://radarr:7878
      - RADARR_API_KEY=your_api_key
      - RADARR_QUALITY_PROFILE=HD-1080p
      
      # Optional variables with defaults
      - NODE_ENV=production
      - LOG_LEVEL=info
      - CHECK_INTERVAL_MINUTES=60
      - RADARR_MINIMUM_AVAILABILITY=released
      
      # Optional root folder ID (if not specified, uses first available)
      # - RADARR_ROOT_FOLDER_ID=1
      
      # Optional movie limiting (both required if using)
      # - LETTERBOXD_TAKE_AMOUNT=10
      # - LETTERBOXD_TAKE_STRATEGY=newest
    restart: unless-stopped